spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001

spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-dept-client
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB01
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.springcloud.entities 
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
eureka: 
  client:
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/
  instance: 
    instance-id: dept-8001.com #更改服务名称
    prefer-ip-address: true #访问路径可以显示ip地址

---
server:
  port: 8001

spring:
  profiles: test #开发环境
  application:
    name: microservicecloud-config-dept-client
  datasource:
    url: jdbc:mysql://localhost:3306/cloudDB01
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.springcloud.entities 
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
eureka: 
  client:
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/
  instance: 
    instance-id: dept-8001.com #更改服务名称
    prefer-ip-address: true #访问路径可以显示ip地址
